### ISSUE TITLE
Unable to Transition Screen After Joining a Room Using Waterbus SDK on iPhone

### ISSUE THREAD

**Issue by dictat** [waterbustech/waterbus-flutter-sdk#20]
I tried to join a room created with the following code, but the screen does not transition (i.e., the UI does not update to show the meeting). I am using a physical iPhone device.

```dart
final meetingUser = await WaterbusSdk.instance.getProfile();
final Meeting? meeting = await WaterbusSdk.instance.joinRoom(
    meeting: _meeting!,
    password: 'password',
    userId: meetingUser!.id);
``` 

As shown in the logs below, it seems that the connection is successful, but the screen does not change.

```yaml
flutter: \^[[38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;12m│ #0   WaterbusLogger.log (package:waterbus_sdk/utils/logger/logger.dart:16:12)<…>
flutter: \^[[38;5;12m│ #1   WebRTCVideoStats._getSenderStats (package:waterbus_sdk/stats/webrtc_video_stats.dart:174:28)<…>
flutter: \^[[38;5;12m├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;12m│ 💡 [WaterbusLogger]: framesSent: 25 | frameHeight: 640 | frameWidth: 480 | framePerSecond: 15.0<…>
flutter: \^[[38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
```

Additional Information:
I am using waterbus_sdk version 1.5.2 as specified in my pubspec.yaml dependencies:
```yaml
dependencies: 
 waterbus_sdk: ^1.5.2
```

Is this feature not yet implemented?
